/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/styles/theme/pancatzTheme.ts
 * Command: astryx theme build src/styles/theme/pancatzTheme.ts
 * Generated: 2026-07-05T17:55:13.883Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const pancatzTheme: DefinedTheme;
